### ISSUE TITLE
Blank screen in iPhone 13 Pro

### ISSUE THREAD

**Issue by V1T3X3** [MochiDoesVR/Caramel-For-VRChat#4]
When I sideloaded the app using sideloadly, the preview screen is black. Although, iOS reports that the camera was recently used for capture. iOS version is 17.3.1.
Also, does this capture LiDAR depth data for true 3D tracking?
Sorry if I'm using the issues tracker wrong, I'm new here.

**Comment by MochiDoesVR** [comment]
Sorry for the late response. Would you mind sharing a screenshot? Like, is there _any_ UI whatsoever, or just a completely blank page?

Regarding your question about the LiDAR sensor, I'm not sure, as I haven't found anything about this in the ARKit documentation, and I don't currently have a Pro series iPhone to test myself.

**Comment by V1T3X3** [comment]
<img src="https://github.com/MochiDoesVR/Caramel-For-VRChat/assets/163378363/bac2eb31-7d0f-4fbf-83d2-e49bd535572d" width="350" />
<img src="https://github.com/MochiDoesVR/Caramel-For-VRChat/assets/163378363/8b606eef-799b-4ccb-9250-5a4940d4933e" width="350" />

Here's the two views of the app, completely blank. I've verified that it is still sending OSC data to VRChat, albeit inaccurate.

![image](https://github.com/MochiDoesVR/Caramel-For-VRChat/assets/163378363/3d2e4ce0-5b69-4c3f-b675-77c3821bf9b6)
This is the article that I read that showcases capturing depth using the LiDAR sensor:
https://developer.apple.com/documentation/avfoundation/additional_data_capture/capturing_depth_using_the_lidar_camera
granted, its about AVFoundation but I tend to hope for the best.

![image](https://github.com/MochiDoesVR/Caramel-For-VRChat/assets/163378363/add9b4c9-7ef2-4596-921c-4e1f5bc70dfa)
https://developer.apple.com/documentation/arkit/arframe/3566299-scenedepth
There's also the sceneDepth property inside ARKit itself. Perhaps you can use it to guesstimate joint position in 3D space?

Btw, I'm talking out of my ass here. Just hoping this might be **the** solution for the masses for FBT, even if its a pipe dream.

**Comment by MochiDoesVR** [comment]
Inaccurate tracking is to be expected, but I couldn't really tell you what's causing the black screen, unless it's some kinda regression linked to iOS 16.x and newer. I haven't really touched iOS development since I released this app, so I can't really do much but offer support.

**Comment by MochiDoesVR** [comment]
Regarding your question about depth, I was looking into trying to use the faceID sensor, or LiDAR sensor for body tracking by utilizing a custom tracking net a long time ago, but never got around to it because ML looked too confusing lol.

**Comment by V1T3X3** [comment]
Fair reasons. Can't really complain since this is a free solution. I think I'll just close this thread with this comment. Hope you good on your future endeavors.
